GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTY4NTY2NDUsImV4cCI6MTYxNjg1NjY2MCwiYXVkIjoiNjA1YTM4NGJlYTE0NWYzNzM4ODI3MTVmIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.0MZpE1XMvRg7i7-R4u30t82pQzQsHzJ34Net7maNfEU


### Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ghum@gmail.com",
    "password": "penguin_pakhi"
}


### Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "ghumaye_gechi@gmail.com",
    "password": "penguin_pakhi"
}

### Refresh Token Route
POST http://localhost:3000/auth/refresh-token

### Logout Route
DELETE http://localhost:3000/auth/logout