GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTc2OTAxNTIsImV4cCI6MTYxNzY5MDE2NywiYXVkIjoiNjA1YTM4NGJlYTE0NWYzNzM4ODI3MTVmIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.Gh5XzFgOeOUxGKx5OtsCPejmytBmtHrHneTiztEyOdc

### Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ghum@gmail.com",
    "password": "penguin_pakhi"
}


### Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "alright@gmail.com",
    "password": "penguin_pakhi"
}

### Refresh Token Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTc2OTAxMTksImV4cCI6MTY0OTI0NzcxOSwiYXVkIjoiNjA1YTM4NGJlYTE0NWYzNzM4ODI3MTVmIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.E4JVZ--DpH9w-ISmegrmQp0-I1LBfvAnUcWqsYdii98"
}

### Logout Route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTc2ODkwNDksImV4cCI6MTY0OTI0NjY0OSwiYXVkIjoiNjA1YTM4NGJlYTE0NWYzNzM4ODI3MTVmIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.51AkEXyUNtc2ZHTI538X29BabWaJtAnMxVb8FgKhRE8"
}